export const LOG_IN = 'LOG_IN';
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_EXAMINATION_DATE = 'GET_EXAMINATION_DATE';
export const POST_EXAMINATION_DATE = 'POST_EXAMINATION_DATE';
export const GET_DIAGNOSTIC_DATE = 'GET_DIAGNOSTIC_DATE';
export const POST_DIAGNOSTIC_DATE = 'POST_DIAGNOSTIC_DATE';
export const GET_EVIDENCE_DATE = 'GET_EVIDENCE_DATE';
export const POST_EVIDENCE_DATE = 'POST_EVIDENCE_DATE';
