export const LOG_IN = 'LOG_IN';
export const GET_LOGGED_USER = 'GET_LOGGED_USER';
export const GET_EXAMINATION_DATE = 'GET_EXAMINATION_DATE';
export const POST_EXAMINATION_DATE = 'POST_EXAMINATION_DATE';
